[project]
name = "pybitbrowser"
version = "0.1.0"
description = "A python library for the BitBrowser browser"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "better-proxy>=1.3.1",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
]
